version: '2'

services:
  rabbitmq:
    image: 'ixwolf/bitnami-docker-rabbitmq:3.7'
    ports:
      - '1883:1883'
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
      - RABBITMQ_USERNAME=slim
      - RABBITMQ_HASHED_PASSWORD=CEDFNEGEJ30cdU9fSaDwAIfdPLFCH1ANUrB2z3FYk27ae6as
volumes:
  rabbitmq_data:
    driver: local
